os:
    - linux
    - osx

language: java

jdk:
    - openjdk11

env:
    - GRAALVM_VERSION="1.0.0-rc8"

install:
    - |
        if [[ "$TRAVIS_OS_NAME" == "osx" ]];   then DOWNLOAD_OS_NAME="macos"; fi
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then DOWNLOAD_OS_NAME="linux"; fi
        curl -LJ "https://github.com/oracle/graal/releases/download/vm-$GRAALVM_VERSION/graalvm-ce-$GRAALVM_VERSION-$DOWNLOAD_OS_NAME-amd64.tar.gz" --output graalvm.tar.gz
        tar -xzf graalvm.tar.gz

script:
    - mvn clean
    - mvn package
    - mvn exec:exec
    - mvn exec:exec@nograal
    - export JAVA_HOME="$(pwd)/graalvm-ce-$GRAALVM_VERSION" && if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME="$JAVA_HOME/Contents/Home"; fi
    - mvn clean
    - mvn package
    - mvn exec:exec
